const fs=require("fs")
const p="c:/Users/valde/Documents/Programs Visual Studio Code/OrdenExpress/frontend/src/pages/EmpleadoDashboard.jsx"
const o=[]
function p(s){o.push(s)}
p("import React from react")
p("import { useCallback, useEffect, useState } from \"react\"")
p("import { Search, DollarSign, PackageCheck, Clock, CheckCircle, XCircle, RefreshCw, ChevronDown, ChevronUp, Volume2, VolumeX, ShoppingBag, Ticket, AlertCircle } from \"lucide-react\"")
p("import { getPedidosRecepcion, cobrarPedido, entregarPedido } from \"../services/recepcionService\"")
p("import { useToast } from \"../components/Toast\"")
p("")
p("const METODOS=[\"Todos\",\"Efectivo\",\"Tarjeta\"];")
p("const ESTADOS=[\"Todos\",\"Pendiente\",\"Pagado\",\"En Preparacion\",\"Listo\",\"Entregado\"];")
p("")
p("const norm=(e)=>{if(!e)return\"?\";if(e.includes(\"Preparaci\"))return\"En Preparacion\";if([\"Pagado\",\"Pendiente\",\"Listo\",\"Entregado\",\"Cancelado\"].includes(e))return e;return e;};")
p("")
p("const badge=(o)=>{const e=norm(o);const m={Pendiente:{bg:\"#FDE68A\",fg:\"#92400E\"},Pagado:{bg:\"#BFDBFE\",fg:\"#1E40AF\"},\"En Preparacion\":{bg:\"#FECACA\",fg:\"#991B1B\"},Listo:{bg:\"#BBF7D0\",fg:\"#166534\"},Entregado:{bg:\"#E9D5FF\",fg:\"#7C3AED\"},Cancelado:{bg:\"#CBD5E1\",fg:\"#475569\"}};return m[e]||m.Pendiente;};")
p("")
p("const safeDate=(d)=>{try{return d?new Date(d):new Date();}catch{return new Date();}};")
p("")
p("const val=(o,...k)=>{for(let x of k){if(o&&typeof o===\"object\"&&x in o)return o[x];}return undefined;};")
p("")
p("const nomProd=(d)=>{const nm=val(d,\"producto\",\"nombre_P\")||val(d,\"producto\",\"Nombre_P\")||val(d,\"Producto\",\"nombre_P\")||val(d,\"Producto\",\"Nombre_P\");if(nm)return nm;const pid=val(d,\"iD_Producto\")||val(d,\"ID_Producto\");return pid?\"Producto #\"+pid:\"Producto\";};")
p("")
p("const fmtM=(n)=>\"$\"+Number(n||0).toFixed(2);")
p("const fmtH=(f)=>{try{return safeDate(f).toLocaleTimeString(\"es-MX\",{hour:\"2-digit\",minute:\"2-digit\"});}catch{return\"--:--\";}};")
p("const nomCl=(p)=>{const n=val(p,\"Cliente\",\"Nombre\");return n?n+\" \"+(val(p,\"Cliente\",\"Apellido_Paterno\")||\"\"):\"Cliente\";};")
p("const gId=(p)=>val(p,\"iD_Pedido\")||val(p,\"ID_Pedido\");")
p("const gDet=(p)=>val(p,\"Detalles\")||[];")
p("const gFol=(p)=>val(p,\"folio\")||val(p,\"Folio\")||\"Sin folio\";")
p("const gTot=(p)=>val(p,\"total\")||val(p,\"Total\")||0;")
p("const gFec=(p)=>val(p,\"fecha\")||val(p,\"Fecha\");")
p("const gMet=(p)=>val(p,\"metodo_Pago\")||\"Efectivo\";")
p("const gEst=(p)=>val(p,\"estado\")||val(p,\"Estado\")||\"?\";")
p("const gCan=(d)=>val(d,\"cantidad\")||val(d,\"Cantidad\")||0;")
p("const gDTot=(d)=>val(d,\"total\")||val(d,\"Total\")||0;")
p("")
p("export default function EmpleadoDashboard() {")
p("  const { addToast } = useToast();")
p("  const [pedidos, setPedidos] = useState([]);")
p("  const [loading, setLoading] = useState(true);")
p("  const [errorMsg, setErrorMsg] = useState(\"\");")
p("  const [busqueda, setBusqueda] = useState(\"\");")
p("  const [filtMet, setFiltMet] = useState(\"Todos\");")
p("  const [filtEst, setFiltEst] = useState(\"Todos\");")
p("  const [expId, setExpId] = useState(null);")
p("  const [modalP, setModalP] = useState(null);")
p("  const [cobrando, setCobrando] = useState(false);")
p("  const [alerta, setAlerta] = useState(false);")
p("")
p("  const cargar = useCallback(() => {")
p("    setLoading(true); setErrorMsg(\"\");")
p("    getPedidosRecepcion().then(data=>{if(Array.isArray(data))setPedidos(data);else{addToast(\"Datos invalidos\",\"error\");setPedidos([]);}}).catch(err=>{const m=err.response?(err.response.status===401?\"Sesion expirada\":err.response.status===403?\"Sin permisos\":\"Error al cargar\"):\"Error al cargar\";setErrorMsg(m);addToast(m,\"error\");}).finally(()=>setLoading(false));")
p("  },[addToast]);")
p("")
p("  useEffect(() => { cargar(); const t=setInterval(cargar,8000); return ()=>clearInterval(t); },[cargar]);")
p("")
p("  const filtrados=pedidos.filter(p=>{const fm=!busqueda||gFol(p).toLowerCase().includes(busqueda.toLowerCase());const mm=filtMet===\"Todos\"||gMet(p)===filtMet;const em=filtEst===\"Todos\"||norm(gEst(p))===filtEst;return fm&&mm&&em;});")
p("  const pend=pedidos.filter(p=>gEst(p)===\"Pendiente\"&&gMet(p)===\"Efectivo\");")
p("  const listos=pedidos.filter(p=>norm(gEst(p))===\"Listo\");")
p("  const entreHoy=pedidos.filter(p=>{try{return gEst(p)===\"Entregado\"&&safeDate(gFec(p)).toDateString()===new Date().toDateString();}catch{return false;}});")
p("  const enProc=pedidos.filter(p=>![\"Entregado\",\"Cancelado\"].includes(norm(gEst(p))));")
p("")
p("  const cobra=(ped)=>{if(gMet(ped)!==\"Efectivo\"){addToast(\"Solo efectivo\",\"warning\");return;}if(gEst(ped)!==\"Pendiente\"){addToast(\"No pendiente\",\"warning\");return;}setModalP(ped);};")
p("  const confCobro=async()=>{if(!modalP)return;setCobrando(true);try{await cobrarPedido(gId(modalP));addToast(\"Cobrado: \"+gFol(modalP),\"success\");setModalP(null);cargar();}catch(e){addToast(e.response&&e.response.data?e.response.data.message:\"Error\",\"error\");}finally{setCobrando(false);}};")
p("  const entrega=async(ped)=>{if(norm(gEst(ped))!==\"Listo\"){addToast(\"Debe estar Listo\",\"warning\");return;}try{await entregarPedido(gId(ped));addToast(\"Entregado: \"+gFol(ped),\"success\");cargar();}catch(e){addToast(e.response&&e.response.data?e.response.data.message:\"Error\",\"error\");}};")
p("")
p("  return (")
p("    <div style={{background:\"#0f0f0f\",minHeight:\"100vh\",padding:28,color:\"#fff\"}}>")
p("      <h1 style={{display:\"flex\",alignItems:\"center\",gap:8,fontSize:22,marginBottom:4}}><ShoppingBag /> Panel de Recepciones</h1>")
p("      <p style={{color:\"#666\",marginBottom:20}}>Pinchos Banderillas</p>")
p("      <button onClick={()=>setAlerta(v=>!v)} style={{marginBottom:16,padding:\"7px 14px\",borderRadius:8,cursor:\"pointer\",background:alerta?\"#16a34a\":\"#333\",color:\"#fff\",border:\"none\",fontSize:12}}>Alerta {alerta?\"ON\":\"OFF\"}</button>")
p("      <button onClick={cargar} style={{marginLeft:8,marginBottom:16,padding:\"7px 14px\",borderRadius:8,cursor:\"pointer\",background:\"#222\",color:\"#aaa\",border:\"1px solid #333\",fontSize:12}}>Actualizar</button>")
p("      <div style={{display:\"grid\",gridTemplateColumns:\"repeat(auto-fit,minmax(150px,1fr))\",gap:12,marginBottom:20}}>")
p("        <StatCard label=\"Por Cobrar\" value={pend.length} color=\"#F59E0B\" desc=\"Efectivo pendiente\"/>")
p("        <StatCard label=\"Listos Entrega\" value={listos.length} color=\"#10B981\" desc=\"Esperan mostrador\"/>")
p("        <StatCard label=\"Entregados Hoy\" value={entreHoy.length} color=\"#6366F1\" desc=\"Completados hoy\"/>")
p("        <StatCard label=\"En Proceso\" value={enProc.length} color=\"#888\" desc=\"Activos\"/>")
p("      </div>")
p("      <input placeholder=\"Buscar folio...\" value={busqueda} onChange={e=>setBusqueda(e.target.value)} style={{width:\"100%\",padding:10,borderRadius:10,border:\"1px solid #333\",background:\"#111\",color:\"#ddd\",fontSize:13,boxSizing:\"border-box\",marginBottom:10}}/>")
p("      <div style={{marginBottom:10,display:\"flex\",gap:8,flexWrap:\"wrap\",alignItems:\"center\"}}>")
p("        <span style={{color:\"#444\",fontSize:12}}>Estado:</span>")
p("        {ESTADOS.map(f=><button key={\`fe-\`+f} onClick={()=>setFiltEst(f)} style={{padding:\"4px 10px\",borderRadius:20,fontSize:11,cursor:\"pointer\",background:filtEst===f?\"#c2410c\":\"transparent\",color:filtEst===f?\"#fff\":\"#777\",border:\"1px solid \"+(filtEst===f?\"#c2410c\":\"#333\")}}>{f}</button>)}")
p("        <span style={{color:\"#444\",fontSize:12}}>Metodo:</span>")
p("        {METODOS.map(f=><button key={\`fm-\`+f} onClick={()=>setFiltMet(f)} style={{padding:\"4px 10px\",borderRadius:20,fontSize:11,cursor:\"pointer\",background:filtMet===f?\"#333\":\"transparent\",color:filtMet===f?\"#fff\":\"#777\",border:\"1px solid \"+(filtMet===f?\"#555\":\"#333\")}}>{f}</button>)}")
p("      </div>")
p("      {filtrados.length===0&&<div style={{textAlign:\"center\",padding:40,color:\"#444\",fontSize:14}}>No se encontraron pedidos</div>}")
p("      {filtrados.map(p=>{const sb=badge(gEst(p));const ne=norm(gEst(p));const exp=expId===gId(p);const pc=gEst(p)===\"Pendiente\"&&gMet(p)===\"Efectivo\";const pe=ne===\"Listo\";const dets=gDet(p);return(")
p("        <div key={\`card-\`+gId(p)} style={{background:\"#1a1a1a\",borderRadius:14,border:\"1px solid #2a2a2a\",marginBottom:10,overflow:\"hidden\"}}>")
p("          <div onClick={()=>setExpId(exp?null:gId(p))} style={{padding:\"14px 16px\",display:\"flex\",justifyContent:\"space-between\",cursor:\"pointer\",alignItems:\"center\"}}>")
p("            <div>")
p("              <span style={{fontFamily:\"monospace\",fontWeight:800,fontSize:15,color:\"#ea580c\"}}>{gFol(p)}</span>")
p("              <span style={{fontSize:10,marginLeft:8,padding:\"2px 8px\",borderRadius:20,fontWeight:700,background:sb.bg,color:sb.fg}}>{ne}</span>")
p("              <span style={{fontSize:10,marginLeft:4,padding:\"2px 8px\",borderRadius:20,fontWeight:700,background:gMet(p)===\"Efectivo\"?\"#065f4620\":\"#1e3a8a20\",color:gMet(p)===\"Efectivo\"?\"#34d399\":\"#93c5fd\"}}>{gMet(p)}</span>")
p("              <div style={{marginTop:4,fontSize:12,color:\"#555\"}}>{nomCl(p)} - {fmtH(gFec(p))}</div>")
p("            </div>")
p("            <div style={{display:\"flex\",alignItems:\"center\",gap:8}}>")
p("              <span style={{fontWeight:800,fontSize:17}}>{fmtM(gTot(p))}</span>")
p("              <span style={{color:\"#444\",fontSize:12}}>{exp?\"^\":\"v\"}</span>")
p("            </div>")
p("          </div>")
p("          {exp&&(")
p("            <div style={{borderTop:\"1px solid #252525\",padding:\"12px 16px\",background:\"#141414\"}}>")
p("              <div style={{marginBottom:10}}>{dets.length===0?<span style={{color:\"#555\",fontSize:12}}>Sin productos</span>:dets.map((d,i)=><div key={\`det-\`+gId(p)+\`-\`+i} style={{display:\"flex\",justifyContent:\"space-between\",fontSize:13,color:\"#aaa\",marginBottom:4}}><span>{gCan(d)}x {nomProd(d)}</span><span style={{color:\"#666\"}}>{fmtM(gDTot(d))}</span></div>)}</div>")
p("              <div style={{display:\"flex\",gap:8,flexWrap:\"wrap\"}}>")
p("                {pc&&<button onClick={e=>{e.stopPropagation();cobra(p);}} style={{padding:\"8px 14px\",borderRadius:10,background:\"#16a34a\",color:\"white\",border:\"none\",fontWeight:700,fontSize:13,cursor:\"pointer\"}}>Cobrar {fmtM(gTot(p))}</button>}")
p("                {pe&&<button onClick={e=>{e.stopPropagation();entrega(p);}} style={{padding:\"8px 14px\",borderRadius:10,background:\"#6366F1\",color:\"white\",border:\"none\",fontWeight:700,fontSize:13,cursor:\"pointer\"}}>Entregar</button>}")
p("                {!pc&&!pe&&<span style={{padding:\"8px 14px\",borderRadius:10,background:\"#333\",color:\"#666\",fontSize:12}}>{ne}</span>}")
p("              </div>")
p("            </div>")
p("          )}")
p("        </div>")
p("      ));});}")
p("      {modalP&&(")
p("        <div style={{position:\"fixed\",inset:0,background:\"rgba(0,0,0,0.85)\",display:\"flex\",alignItems:\"center\",justifyContent:\"center\",zIndex:1000}} onClick={()=>!cobrando&&setModalP(null)}>")
p("          <div style={{background:\"#fff\",borderRadius:20,padding:32,maxWidth:400,color:\"#222\",boxShadow:\"0 20px 60px rgba(0,0,0,0.6)\"}} onClick={e=>e.stopPropagation()}>")
p("            <h3 style={{margin:\"0 0 16px\",fontSize:18,fontWeight:800}}>Cobrar pedido {gFol(modalP)}</h3>")
p("            <div style={{display:\"flex\",justifyContent:\"space-between\",alignItems:\"center\",marginBottom:20,fontSize:14,color:\"#555\"}}><span>Total a cobrar</span><strong style={{fontSize:24,color:\"#c2410c\"}}>{fmtM(gTot(modalP))}</strong></div>")
p("            <button onClick={confCobro} disabled={cobrando} style={{width:\"100%\",padding:13,borderRadius:12,background:\"#c2410c\",color:\"white\",border:\"none\",fontWeight:700,fontSize:15,marginBottom:8,cursor:cobrando?\"not-allowed\":\"pointer\",opacity:cobrando?0.7:1}}>{cobrando?\"Cobrando...\":\"Confirmar Cobro\"}</button>")
p("            <button onClick={()=>setModalP(null)} style={{width:\"100%\",padding:11,borderRadius:12,background:\"transparent\",color:\"#555\",border:\"1px solid #ccc\",fontWeight:600,cursor:\"pointer\"}}>Cancelar</button>")
p("          </div>")
p("        </div>")
p("      )}")
p("    </div>")
p("  );")
p("}")
p("")
p("function StatCard({label,value,color,desc}) {")
p("  return (")
p("    <div style={{background:\"#1a1a1a\",borderRadius:12,padding:16,border:\"1px solid #2a2a2a\"}}>")
p("      <div style={{display:\"flex\",alignItems:\"center\",gap:10}}>")
p("        <div style={{background:color+\"20\",borderRadius:10,padding:\"8px 10px\",fontSize:12,fontWeight:900,color:color}}>{label.charAt(0)}</div>")
p("        <div>")
p("          <p style={{color:\"#444\",fontSize:10,margin:0}}>{label}</p>")
p("          <p style={{fontSize:26,fontWeight:800,color:color,margin:0,lineHeight:1}}>{value}</p>")
p("        </div>")
p("      </div>")
p("      <p style={{color:\"#444\",fontSize:11,marginTop:8,marginBottom:0}}>{desc}</p>")
p("    </div>")
p("  );")
p("}")
p("")
p("export default EmpleadoDashboard;")
p("")
fs.writeFileSync(p,o.join(String.fromCharCode(10)));console.log(fs.statSync(p).size)
